INSERT INTO Source (name, url, active, priority) values ('Reddit - /r/netsec', 'https://www.reddit.com/r/netsec/new/.rss', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('XKCD', 'https://xkcd.com/rss.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Reuters - Technology', 'http://feeds.reuters.com/reuters/technologyNews', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('EFF Updates', 'https://www.eff.org/rss/updates.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Lawrence Lessig - Blog', 'http://www.lessig.org/feed/', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Groklaw', 'http://www.groklaw.net/backend/GrokLaw.rdf', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('SANS ISC News', 'https://isc.sans.edu/rssfeed.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Ars Technica - tech', 'http://feeds.arstechnica.com/arstechnica/technology-lab', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Ars Technica - tech policy', 'http://feeds.arstechnica.com/arstechnica/tech-policy', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('CNBC - Tech/Business', 'https://www.cnbc.com/id/19854910/device/rss/rss.html', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Register - Security', 'https://www.theregister.co.uk/security/headlines.atom', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Register - DevOps', 'https://www.theregister.co.uk/devops/headlines.atom', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Register - BOFH', 'https://www.theregister.co.uk/data_centre/bofh/headlines.atom', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Real News Network', 'https://therealnews.com/feed', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('ARRL', 'http://www.arrl.org/news/rss', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Alternet', 'http://www.alternet.org/home/feed', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Wired', 'http://feeds.wired.com/wired/index', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('CBS - TechTalk', 'http://www.cbsnews.com/rss/tech_talk.rss', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('ABC - Tech', 'http://feeds.abcnews.com/abcnews/technologyheadlines', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Washington Times - Tech', 'http://www.washingtontimes.com/rss/headlines/culture/technology/', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('NBC - Tech/Science', 'http://rss.msnbc.msn.com/id/3032117/device/rss/rss.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('freenode', 'https://freenode.net/news/rss.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('GRC - Blog', 'http://feeds.feedburner.com/GibsonResearchNews', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Guardian - UK', 'https://feeds.theguardian.com/theguardian/uk/rss', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Ed Felten - Freedom to Tinker', 'https://freedom-to-tinker.com/feed/', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('techdirt', 'http://feeds.feedburner.com/techdirt/feed', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Sky News - Technology', 'http://feeds.skynews.com/feeds/rss/technology.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Sky News - Strange News', 'http://feeds.skynews.com/feeds/rss/strange.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('ISC', 'http://isc.sans.edu/rssfeed.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('IC3.gov News', 'http://www.ic3.gov/rss/news.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Smithsonian Science', 'http://feeds.feedburner.com/smithsonianmag/science-nature?format=xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Atlantic - WireSvc', 'http://feeds.feedburner.com/TheAtlanticWire?format=xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Atlantic - Politics', 'http://feeds.feedburner.com/AtlanticPoliticsChannel?format=xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('XKCD What-If', 'https://what-if.xkcd.com/feed.atom', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('The Economist - Tech', 'https://www.economist.com/science-and-technology/rss.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Telegraph - Technology', 'https://www.telegraph.co.uk/technology/rss.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Wall Street Journal - Tech', 'https://feeds.a.dj.com/rss/RSSWSJD.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Time - Tech', 'https://feeds.feedburner.com/timeblogs/nerd_world', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Sydney Morning Herald - Technology', 'http://www.smh.com.au/rssheadlines/technology/article/rss.xml', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Google News - Technology', 'https://news.google.com/news?cf=all&hl=en&pz=1&ned=us&topic=tc&output=rss', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Hacker News', 'https://news.ycombinator.com/rss', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Times of India - Tech', 'http://timesofindia.indiatimes.com/rssfeeds/5880659.cms', 1, 1);
--INSERT INTO Source (name, url, active, priority) values ('Google News - Philippines', 'https://news.google.com/news/rss/headlines/section/topic/NATION.en_ph/Philippines?ned=en_ph&hl=en', 1, 1);
--INSERT INTO Source (name, url, active, priority) values ('Twitter - @AP_Europe', 'https://queryfeed.net/twitter?q=from%3AAP_Europe&title-type=user-name-both&geocode=', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('Axios - Technology', 'https://api.axios.com/feed/technology/', 1, 1);
INSERT INTO Source (name, url, active, priority) values ('OANN - Tech', 'http://www.oann.com/category/tech/feed', 1, 1);
